### PR TITLE
Update quotes.json

### PR DESCRIPTION
**Pull request by udit9876gupta**
added 6 quotes

### CODE REVIEW

**Comment by udit9876gupta** [comment]
> added 6 quotes

updated 5 quotes from 91-95 ids

**Review by JWW127 — CHANGES_REQUESTED** [review]
This is pretty good, but a few changes are needed. You'll notice the issue you picked corresponds with quotes ids 91-95. So ids need to be changed to 91,92,93,94,95. Also you this issues in only in need of 5 quotes, as we need to leave room for other hacktoberfest participants.

**Review by JWW127 — APPROVED** [review]
this one looks good

**Comment by udit9876gupta** [comment]
i updated the quotes accroding to the given ids. please check again.

**Comment by JWW127** [comment]
Super. It's been merged. Great Work

**Pull request merged**
